### PR TITLE
Bump Mender-UBoot to mender-rpi-2020.01

### PR DESCRIPTION
**Pull request by oleorhagen**
This fixes the incompatibilities present in the current version, with the newer
RaspiOS images.

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
If you have tested it both on Rpi3 and Rpi4 this is good to go.

Simple fix but hard debugging! Nice job.

**Comment by oleorhagen** [comment]
Not tested on Pi3, but I'll do it, since it seems required. 

Holding off on the merge

**Review by kacf — APPROVED** [review]
The best kind of fix: Having someone else fix it! :stuck_out_tongue_winking_eye:

**Comment by oleorhagen** [comment]
Pi3 is also happy :smile: 
Merging

**Pull request merged**
